// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDMaNwbCrO3Tj5kelE0JOFSZBY6RCBm-k',
    appId: '1:626108133045:web:bd48118bab399012a198fc',
    messagingSenderId: '626108133045',
    projectId: 'fleet-management-6099c',
    authDomain: 'fleet-management-6099c.firebaseapp.com',
    storageBucket: 'fleet-management-6099c.appspot.com',
    measurementId: 'G-RTMGZPRZGQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJGl4WHb2slqIjrVRX4NX06X92GVl3X_8',
    appId: '1:626108133045:android:161ddcccf1320828a198fc',
    messagingSenderId: '626108133045',
    projectId: 'fleet-management-6099c',
    storageBucket: 'fleet-management-6099c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm7dXw0HRntFGPVEEIv_R4iMuyMdCQQ1k',
    appId: '1:626108133045:ios:a19613a76bd8897ea198fc',
    messagingSenderId: '626108133045',
    projectId: 'fleet-management-6099c',
    storageBucket: 'fleet-management-6099c.appspot.com',
    iosBundleId: 'com.example.truckFleetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm7dXw0HRntFGPVEEIv_R4iMuyMdCQQ1k',
    appId: '1:626108133045:ios:a19613a76bd8897ea198fc',
    messagingSenderId: '626108133045',
    projectId: 'fleet-management-6099c',
    storageBucket: 'fleet-management-6099c.appspot.com',
    iosBundleId: 'com.example.truckFleetApp',
  );
}
